---
# tasks file for preparing the nodes

# Check if a public key is provided
- fail:
    msg: "Please provide a public key by passing --extra-vars \"public_key=~/.ssh/id_rsa.pub\""
  when: public_key is not defined

- name: Set master ip as var
  set_fact:
    master_ip: "{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}"
  with_items:
    - "{{ groups['master'] }}"

- name: Add interface
  lineinfile:
      path: /etc/dhcpcd.conf
      line: 'interface {{ ansible_default_ipv4.interface }}'
- name: Add static ip
  lineinfile:
      path: /etc/dhcpcd.conf
      line: 'static ip_address={{ ansible_default_ipv4.address }}/24'
- name: Add static routers
  lineinfile:
      path: /etc/dhcpcd.conf
      line: 'static routers={{ ansible_default_ipv4.gateway }}'
- name: Add static domain_name_servers
  lineinfile:
      path: /etc/dhcpcd.conf
      line: 'static domain_name_servers={{ ansible_default_ipv4.gateway }}'

- name: Change gpu memory to 16mb
  replace:
    dest: /boot/config.txt
    regexp: '^gpu_mem=(\d*)'
    replace: '\0gpu_mem=16'

- name: Set authorized key
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', public_key) }}"

- name: Disallow password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  become: true

- name: Add master to hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ master_ip }}  {{ groups['master'] }}"

- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible Reboot for prepare changes"
  async: 1
  poll: 0
  ignore_errors: True
  tags:
    - boot
    - shutdown

- name: Wait for Reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 20
    timeout: 180
  become: False
  tags:
    - boot
    - shutdown
